#!/bin/bash

resw=2560
resh=1440
res=${resw}x${resh}

walname=$(basename ${1} | cut -d'.' -f1)

cache=$HOME/.cache/paperWiz/

grey=${cache}/grey.png
small=${cache}/small/${walname}small.png
large=${cache}/large/${walname}large.png
over=${cache}/over/${walname}over.png
maincolsmall=${cache}/maincolsmall/${walname}maincolsmall.png
maincollarge=${cache}/maincollarge/${walname}maincollarge.png
maincolover=${cache}/maincolover/${walname}maincolover.png

{
	feh --bg-fill ${1} ${grey}
	wal -i ${1} -n
	xdotool key Alt_L+F5
	pywal-discord -t default
	wal_steam.py 
} &> /dev/null

walresw=$(identify -format '%w' ${1})
walresh=$(identify -format '%h' ${1})


if [[ ${2} -le "1" ]] || [[ -z ${2} ]]
then
	color4=$(cat ~/.cache/wal/colors.sh | grep color4 | cut -d"'" -f2)
	convert -size 2x2 xc:${color4} ${small}
	feh --bg-fill ${small}
	if [[ ${walresw} -ge ${resw} ]] && [[ ${walresh} -ge ${resh} ]]
	then
		feh --bg-fill ${1} ${small}
	else	
		convert -size ${res} xc:${color4} ${large}
		if [[ -z ${3} ]]
		then
			magick composite -gravity center ${1} ${large} ${over}
		else
			magick composite -gravity south ${1} ${large} ${over}
		fi
		feh --bg-fill ${over} ${small}
	fi
fi

if [[ ${2} -ge "2" ]]
then
	maincol=$(convert ${1} -define histogram:unique-colors=true -format %c histogram:info:- | sort -n | sed '$!d' | cut -d'#' -f2 | cut -c1-6)
	convert -size 2x2 xc:\#${maincol} ${maincolsmall}
	feh --bg-fill ${maincolsmall}
	if [[ ${walresw} -ge ${resw} ]] && [[ ${walresh} -ge ${resh} ]]
	then
		feh --bg-fill ${1} ${maincolsmall}
	else	
		convert -size ${res} xc:'#'${maincol} ${maincollarge}
		if [[ -z ${3} ]]
		then
			magick composite -gravity center ${1} ${maincollarge} ${maincolover}
		else
			magick composite -gravity south ${1} ${maincollarge} ${maincolover}
		fi	
		feh --bg-fill ${maincolover} ${maincolsmall}
	fi
fi

#echo ${1}
#echo ${2}
#echo ${3}
#echo ${resw}
#echo ${resh}
#echo ${walname}
#echo ${cache}
#echo ${walresw} 
#echo ${walresh}
#echo ${color4}
#echo ${maincol}
