#!/bin/bash

###############################

# Set your resolution here
resw=2560
resh=1440
res=${resw}x${resh}

# Cache location
cache=$HOME/.cache/paperWiz/

###############################

# Help Menu
usage() {
	cat <<EOF

Usage:
  paperWiz [options] <image>

Description:
  Sets your second monitors wallpapers to a single color and surrounds images with
  a lower resolution than your monitor with a colored border

Options:
  -h, --help	Show help menu
  -p, --pywal	Use color4 from pywal
  -m, --magick	Use the images main color
  -c, --center	Send the image to the center of the screen
  -s, --south	Send the image to the bottom of the screen

EOF
}
[[ ${1} = "-h" ]] && usage && exit 0
# Sets the main wallpaper and grey as the wallpaper for the second monitor. Also refreshes programs that require it for pywal.

[[ ${1} != "-h" ]] && {
	feh --bg-fill ${1} ${grey}
	wal -i ${1} -n
	xdotool key Alt_L+F5
	pywal-discord -t default
	wal_steam.py 
} &> /dev/null

# Where to cache each image
grey=${cache}/grey.png
small=${cache}/small/${walname}small.png
large=${cache}/large/${walname}large.png
over=${cache}/over/${walname}over.png
maincolsmall=${cache}/maincolsmall/${walname}maincolsmall.png
maincollarge=${cache}/maincollarge/${walname}maincollarge.png
maincolover=${cache}/maincolover/${walname}maincolover.png

# Grabs the wallpaper name to use for cached images
walname=$(basename ${1} | cut -d'.' -f1)

# Fetches the wallpapers resolution
walresw=$(identify -format '%w' ${1})
walresh=$(identify -format '%h' ${1})

# color4
if [[ ${2} -le "1" ]] || [[ -z ${2} ]]
then
	color4=$(cat ~/.cache/wal/colors.sh | grep color4 | cut -d"'" -f2)
	convert -size 2x2 xc:${color4} ${small}
	feh --bg-fill ${small}
	if [[ ${walresw} -ge ${resw} ]] && [[ ${walresh} -ge ${resh} ]]
	then
		feh --bg-fill ${1} ${small}
	else	
		convert -size ${res} xc:${color4} ${large}
		if [[ -z ${3} ]]
		then
			magick composite -gravity center ${1} ${large} ${over}
		else
			magick composite -gravity south ${1} ${large} ${over}
		fi
		feh --bg-fill ${over} ${small}
	fi
fi

# main color
if [[ ${2} -ge "2" ]]
then
	maincol=$(convert ${1} -define histogram:unique-colors=true -format %c histogram:info:- | sort -n | sed '$!d' | cut -d'#' -f2 | cut -c1-6)
	convert -size 2x2 xc:\#${maincol} ${maincolsmall}
	feh --bg-fill ${maincolsmall}
	if [[ ${walresw} -ge ${resw} ]] && [[ ${walresh} -ge ${resh} ]]
	then
		feh --bg-fill ${1} ${maincolsmall}
	else	
		convert -size ${res} xc:'#'${maincol} ${maincollarge}
		if [[ -z ${3} ]]
		then
			magick composite -gravity center ${1} ${maincollarge} ${maincolover}
		else
			magick composite -gravity south ${1} ${maincollarge} ${maincolover}
		fi	
		feh --bg-fill ${maincolover} ${maincolsmall}
	fi
fi

#echo ${1}
#echo ${2}
#echo ${3}
#echo ${resw}
#echo ${resh}
#echo ${walname}
#echo ${cache}
#echo ${walresw} 
#echo ${walresh}
#echo ${color4}
#echo ${maincol}
